config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  get "home/index"

  resources :venues

  resources :meetings

  resources :exibitors

  resources :sponsors

  resources :exibitor_categories
  
  root :to => 'home#index'

end

app/models/exibitor_category.rb
class ExibitorCategory < ActiveRecord::Base
  attr_accessible :name
  has_many :exibitor
  validates :name, :presence => true
end

app/controllers/exibitor_categories_controller.rb
class ExibitorCategoriesController < ApplicationController
  # GET /exibitor_categories
  # GET /exibitor_categories.json
  def index
    @exibitor_categories = ExibitorCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exibitor_categories }
    end
  end

  # GET /exibitor_categories/1
  # GET /exibitor_categories/1.json
  def show
    @exibitor_category = ExibitorCategory.find(params[:id])
    @exibitors_in_category = @exibitor_category.exibitor

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exibitor_category }
    end
  end

  # GET /exibitor_categories/new
  # GET /exibitor_categories/new.json
  def new
    @exibitor_category = ExibitorCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exibitor_category }
    end
  end

  # GET /exibitor_categories/1/edit
  def edit
    @exibitor_category = ExibitorCategory.find(params[:id])
  end

  # POST /exibitor_categories
  # POST /exibitor_categories.json
  def create
    @exibitor_category = ExibitorCategory.new(params[:exibitor_category])

    respond_to do |format|
      if @exibitor_category.save
        format.html { redirect_to @exibitor_category, notice: 'Exibitor category was successfully created.' }
        format.json { render json: @exibitor_category, status: :created, location: @exibitor_category }
      else
        format.html { render action: "new" }
        format.json { render json: @exibitor_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exibitor_categories/1
  # PUT /exibitor_categories/1.json
  def update
    @exibitor_category = ExibitorCategory.find(params[:id])

    respond_to do |format|
      if @exibitor_category.update_attributes(params[:exibitor_category])
        format.html { redirect_to @exibitor_category, notice: 'Exibitor category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exibitor_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exibitor_categories/1
  # DELETE /exibitor_categories/1.json
  def destroy
    @exibitor_category = ExibitorCategory.find(params[:id])
    @exibitor_category.destroy

    respond_to do |format|
      format.html { redirect_to exibitor_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exibitor_categories_helper.rb
module ExibitorCategoriesHelper
end

app/views/exibitor_categories/_form.html.erb
<%= form_for(@exibitor_category) do |f| %>
  <% if @exibitor_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exibitor_category.errors.count, "error") %> prohibited this exibitor_category from being saved:</h2>

      <ul>
      <% @exibitor_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exibitor_categories/edit.html.erb
<h1>Editing exibitor_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @exibitor_category %> |
<%= link_to 'Back', exibitor_categories_path %>

app/views/exibitor_categories/index.html.erb
<h1>Listing exibitor_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exibitor_categories.each do |exibitor_category| %>
  <tr>
    <td><%= exibitor_category.name %></td>
    <td><%= link_to 'Show', exibitor_category %></td>
    <td><%= link_to 'Edit', edit_exibitor_category_path(exibitor_category) %></td>
    <td><%= link_to 'Destroy', exibitor_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exibitor category', new_exibitor_category_path %>

app/views/exibitor_categories/new.html.erb
<h1>New exibitor_category</h1>

<%= render 'form' %>

<%= link_to 'Back', exibitor_categories_path %>

app/views/exibitor_categories/show.html.erb
<div id="floatbox">
	<strong>Exibitors</strong><br />
	<% @exibitors_in_category.each do |e| %>
		<%= e.name %> <br /><br />
	<% end %>
</div>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exibitor_category.name %>
</p>


<%= link_to 'Edit', edit_exibitor_category_path(@exibitor_category) %> |
<%= link_to 'Back', exibitor_categories_path %>