config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  get "home/index"

  resources :venues

  resources :meetings

  resources :exibitors

  resources :sponsors

  resources :exibitor_categories
  
  root :to => 'home#index'

end

app/models/exibitor.rb
class Exibitor < ActiveRecord::Base
  attr_accessible :description, :exibitor_category_id, :name, :sponsor_id
  belongs_to :exibitor_category
  belongs_to :sponsor
  has_many :meeting, :through => :sponsor
  validates :name, :presence => true
  validates :description, :presence => true
  validates :exibitor_category_id, :presence => true
  validates :sponsor_id, :presence => true
end

app/controllers/exibitors_controller.rb
class ExibitorsController < ApplicationController
  # GET /exibitors
  # GET /exibitors.json
  def index
    @exibitors = Exibitor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exibitors }
    end
  end

  # GET /exibitors/1
  # GET /exibitors/1.json
  def show
    @exibitor = Exibitor.find(params[:id])
    @exibitormeetings = @exibitor.sponsor.meeting

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exibitor }
    end
  end

  # GET /exibitors/new
  # GET /exibitors/new.json
  def new
    @exibitor = Exibitor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exibitor }
    end
  end

  # GET /exibitors/1/edit
  def edit
    @exibitor = Exibitor.find(params[:id])
  end

  # POST /exibitors
  # POST /exibitors.json
  def create
    @exibitor = Exibitor.new(params[:exibitor])

    respond_to do |format|
      if @exibitor.save
        format.html { redirect_to @exibitor, notice: 'Exibitor was successfully created.' }
        format.json { render json: @exibitor, status: :created, location: @exibitor }
      else
        format.html { render action: "new" }
        format.json { render json: @exibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exibitors/1
  # PUT /exibitors/1.json
  def update
    @exibitor = Exibitor.find(params[:id])

    respond_to do |format|
      if @exibitor.update_attributes(params[:exibitor])
        format.html { redirect_to @exibitor, notice: 'Exibitor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exibitors/1
  # DELETE /exibitors/1.json
  def destroy
    @exibitor = Exibitor.find(params[:id])
    @exibitor.destroy

    respond_to do |format|
      format.html { redirect_to exibitors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exibitors_helper.rb
module ExibitorsHelper
end

app/views/exibitors/_form.html.erb
<%= form_for(@exibitor) do |f| %>
  <% if @exibitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exibitor.errors.count, "error") %> prohibited this exibitor from being saved:</h2>

      <ul>
      <% @exibitor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :sponsor_id %><br />
    <%= f.select :sponsor_id, Sponsor.all.collect {|sponsor| [ sponsor.url, sponsor.id ] } %>
  </div>
  <div class="field">
    <%= f.label :exibitor_category_id %><br />
    <%= f.select :exibitor_category_id, ExibitorCategory.all.collect {|exibitor_category| [ exibitor_category.name, exibitor_category.id ] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exibitors/edit.html.erb
<h1>Editing exibitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @exibitor %> |
<%= link_to 'Back', exibitors_path %>

app/views/exibitors/index.html.erb
<h1>Listing exibitors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Sponsor</th>
    <th>Exibitor category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exibitors.each do |exibitor| %>
  <tr>
    <td><%= exibitor.name %></td>
    <td><%= exibitor.description %></td>
    <td><%= exibitor.sponsor.url %></td>
    <td><%= exibitor.exibitor_category.name %></td>
    <td><%= link_to 'Show', exibitor %></td>
    <td><%= link_to 'Edit', edit_exibitor_path(exibitor) %></td>
    <td><%= link_to 'Destroy', exibitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exibitor', new_exibitor_path %>

app/views/exibitors/new.html.erb
<h1>New exibitor</h1>

<%= render 'form' %>

<%= link_to 'Back', exibitors_path %>

app/views/exibitors/show.html.erb
<div id="floatbox">
	<strong>Meetings</strong><br />
	<% @exibitormeetings.each do |m| %>
		<i>Title: </i><%= m.name %> <br />
		<i>Date: </i><%= m.start_date%><br /><br />
	<% end %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exibitor.name %>
</p>

<p>
  <b>Description:</b>
  <%= @exibitor.description %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @exibitor.sponsor.url %>
</p>

<p>
  <b>Exibitor category:</b>
  <%= @exibitor.exibitor_category.name %>
</p>


<%= link_to 'Edit', edit_exibitor_path(@exibitor) %> |
<%= link_to 'Back', exibitors_path %>